Milestone 2 - Structure
men32z/redux-bookstore pull request #2
Opened 2020-02-25 20:11 UTC by men32z

The basic structure of the project wich includes
- folder structure
- Basic components, App, Book 
- Basic Containers, BooksForm, BookList
- Redux integration
- Reducers and Actions.

2020-02-25 20:12 UTC, men32z commented
*** I have Microverse permit to work alone on this project.

2020-02-26 20:02 UTC, azdrenymeri requested changes
### Hello @men32z :wave: 
### Good job on this milestone :+1: 
#### There is an error with prop types inside `BookList` Container.
![scr](https://i.ibb.co/MCZDfbH/Screenshot-from-2020-02-26-20-59-43.png)

### Kindly fix this error and add it for another review

2020-02-26 20:02 UTC, azdrenymeri commented on src/index.js
> +ReactDOM.render(<Provider store={store}><App /></Provider>, document.getElementById('root'));
Based on the requirements of the project you should wrap `App` with `Provider` and assing the whole thing to a variable, then pass it to the `ReactDOM.render()` function.
ex:
```javascript
const wrappedApp = (
  <Provider store={store}>
    <App />
  </Provider>
);
ReactDOM.render(wrappedApp, document.getElementById('root'));
```

2020-02-26 20:58 UTC, men32z commented on src/index.js
> +ReactDOM.render(<Provider store={store}><App /></Provider>, document.getElementById('root'));
Thanks I'll fix the errors.

2020-02-27 21:19 UTC, Oghenebrume50 approved these changes
### STATUS: APPROVED 

Hi @men32z good job on making changes, everything works fine now, please merge and move to the next milestone :+1:  

**RAPHAEL NORIODE** :sunglasses:

2020-02-27 21:52 UTC, merged